export const PROJECT_STORAGE_KEY = 'klattsch-studio.project.v1';
export const SONG_MIME = 'application/vnd.klattsch.song+json';
export const SONG_EXTENSION = '.klattschsong.json';
export const DEFAULT_VIDEO_MIME_CANDIDATES = [
  'video/mp4;codecs=avc1.42E01E,mp4a.40.2',
  'video/mp4',
  'video/webm;codecs=vp9,opus',
  'video/webm',
];

export const SNAP_BEAT = 0.25;
export const PIXELS_PER_BEAT = 68;
export const ROW_HEIGHT = 28;
export const LANE_COUNT = 25;
export const MAX_PITCH_OFFSET = 12;
export const MIN_PITCH_OFFSET = -12;
export const AUDIO_SAMPLE_RATE = 48000;

export const PITCH_LANES = Array.from(
  { length: LANE_COUNT },
  (_, index) => MAX_PITCH_OFFSET - index,
);

export const CLIP_COLORS = [
  'sunset',
  'acid',
  'teal',
  'violet',
  'amber',
  'crimson',
];

export const EFFECT_PARAMS = {
  pitchOffset: {
    label: 'Pitch Offset',
    shortLabel: 'Pitch',
    min: -12,
    max: 12,
    step: 0.25,
    defaultValue: 0,
    format: (value) => `${Number(value).toFixed(2)} st`,
  },
  rate: {
    label: 'Rate',
    shortLabel: 'Rate',
    directive: 'r',
    min: 40,
    max: 240,
    step: 1,
    defaultValue: 110,
    format: (value) => `${Math.round(value)} ms`,
  },
  scale: {
    label: 'Formant Scale',
    shortLabel: 'Scale',
    directive: 's',
    min: 0.7,
    max: 1.5,
    step: 0.01,
    defaultValue: 1,
    format: (value) => Number(value).toFixed(2),
  },
  vibratoDepth: {
    label: 'Vibrato Depth',
    shortLabel: 'Vib Amt',
    directive: 'v',
    min: 0,
    max: 18,
    step: 0.1,
    defaultValue: 0,
    format: (value) => `${Number(value).toFixed(1)} Hz`,
  },
  vibratoRate: {
    label: 'Vibrato Rate',
    shortLabel: 'Vib Rate',
    directive: 'w',
    min: 1,
    max: 12,
    step: 0.1,
    defaultValue: 5,
    format: (value) => `${Number(value).toFixed(1)} Hz`,
  },
  tremoloDepth: {
    label: 'Tremolo Depth',
    shortLabel: 'Trem Amt',
    directive: 'm',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 0,
    format: (value) => Number(value).toFixed(2),
  },
  tremoloRate: {
    label: 'Tremolo Rate',
    shortLabel: 'Trem Rate',
    directive: 'n',
    min: 0.5,
    max: 15,
    step: 0.1,
    defaultValue: 5,
    format: (value) => `${Number(value).toFixed(1)} Hz`,
  },
  aspiration: {
    label: 'Aspiration',
    shortLabel: 'Air',
    directive: 'h',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 0,
    format: (value) => Number(value).toFixed(2),
  },
  tilt: {
    label: 'Spectral Tilt',
    shortLabel: 'Tilt',
    directive: 't',
    min: -0.9,
    max: 0.9,
    step: 0.01,
    defaultValue: 0,
    format: (value) => Number(value).toFixed(2),
  },
  effort: {
    label: 'Vocal Effort',
    shortLabel: 'Effort',
    directive: 'g',
    min: 0,
    max: 1,
    step: 0.01,
    defaultValue: 0.5,
    format: (value) => Number(value).toFixed(2),
  },
};

export const AUTOMATION_PARAM_KEYS = [
  'pitchOffset',
  'rate',
  'scale',
  'vibratoDepth',
  'vibratoRate',
  'tremoloDepth',
  'tremoloRate',
  'aspiration',
  'tilt',
  'effort',
];

export const CLIP_EFFECT_KEYS = [
  'scale',
  'vibratoDepth',
  'vibratoRate',
  'tremoloDepth',
  'tremoloRate',
  'aspiration',
  'tilt',
  'effort',
];

export const DEFAULT_MASTER = Object.freeze({
  title: 'Klattsch Studio Session',
  bank: 'klatt1980-en',
  tempo: 128,
  baseF0: 140,
  rate: EFFECT_PARAMS.rate.defaultValue,
  scale: EFFECT_PARAMS.scale.defaultValue,
  vibratoDepth: EFFECT_PARAMS.vibratoDepth.defaultValue,
  vibratoRate: EFFECT_PARAMS.vibratoRate.defaultValue,
  tremoloDepth: EFFECT_PARAMS.tremoloDepth.defaultValue,
  tremoloRate: EFFECT_PARAMS.tremoloRate.defaultValue,
  aspiration: EFFECT_PARAMS.aspiration.defaultValue,
  tilt: EFFECT_PARAMS.tilt.defaultValue,
  effort: EFFECT_PARAMS.effort.defaultValue,
  outputVolume: 1,
});

export const VOICE_PRESETS = [
  {
    id: 'classic',
    label: 'Classic Default',
    bank: 'klatt1980-en',
    baseF0: 140,
    rate: 110,
    scale: 1,
    vibratoDepth: 0,
    vibratoRate: 5,
    tremoloDepth: 0,
    tremoloRate: 5,
    aspiration: 0,
    tilt: 0,
    effort: 0.5,
  },
  {
    id: 'deep-narrator',
    label: 'Deep Narrator',
    bank: 'klatt1980-en',
    baseF0: 108,
    rate: 118,
    scale: 0.88,
    vibratoDepth: 0.2,
    vibratoRate: 4.3,
    tremoloDepth: 0.02,
    tremoloRate: 4.6,
    aspiration: 0.03,
    tilt: -0.22,
    effort: 0.74,
  },
  {
    id: 'bright-soprano',
    label: 'Bright Soprano',
    bank: 'klatt1980-en',
    baseF0: 220,
    rate: 102,
    scale: 1.18,
    vibratoDepth: 2.1,
    vibratoRate: 5.9,
    tremoloDepth: 0.03,
    tremoloRate: 6.2,
    aspiration: 0.06,
    tilt: 0.12,
    effort: 0.58,
  },
  {
    id: 'airy-dream',
    label: 'Airy Dream',
    bank: 'klatt1980-en',
    baseF0: 176,
    rate: 108,
    scale: 1.08,
    vibratoDepth: 1.3,
    vibratoRate: 5.2,
    tremoloDepth: 0.05,
    tremoloRate: 6.8,
    aspiration: 0.18,
    tilt: 0.05,
    effort: 0.42,
  },
  {
    id: 'tokyo-sketch',
    label: 'Tokyo Sketch',
    bank: 'ja-mokhtari-2000',
    baseF0: 188,
    rate: 104,
    scale: 1,
    vibratoDepth: 1,
    vibratoRate: 5.5,
    tremoloDepth: 0.02,
    tremoloRate: 6,
    aspiration: 0.08,
    tilt: 0.02,
    effort: 0.5,
  },
  {
    id: 'hecko-bright',
    label: 'Hecko Bright',
    bank: 'ja-hecko-2026',
    baseF0: 168,
    rate: 96,
    scale: 0.98,
    vibratoDepth: 0.7,
    vibratoRate: 5,
    tremoloDepth: 0.02,
    tremoloRate: 7.2,
    aspiration: 0.04,
    tilt: -0.05,
    effort: 0.64,
  },
  {
    id: 'cobalt-robot',
    label: 'Cobalt Robot',
    bank: 'klatt1980-en',
    baseF0: 150,
    rate: 90,
    scale: 0.93,
    vibratoDepth: 0,
    vibratoRate: 5,
    tremoloDepth: 0.12,
    tremoloRate: 8.5,
    aspiration: 0.01,
    tilt: -0.28,
    effort: 0.88,
  },
];

export const IMPORT_TEMPLATES = {
  sentence: 'Type a sentence here. The studio will turn it into valid klattsch protocol.',
  protocol: 'Paste raw klattsch code here. The studio will break it into editable clips.',
};
